import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ContextBase from "@/components/context";
import Footer from "@/components/Footer";
// import { Providers } from "./providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body >
        {/* <Providers> */}
          <ContextBase>
            <Navbar />
            {children}
            <Footer />
          </ContextBase>
        {/* </Providers> */}
      </body>
    </html>
  );
}
